spring.application.name=accounts
#server.port=8081

# DB properties
spring.datasource.url=jdbc:postgresql://localhost:5432/accounts
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate properties
spring.jpa.hibernate.ddl-auto=create-drop

# External APIs
user.api.url=https://7srbth8d59.execute-api.eu-central-1.amazonaws.com/live/users/
user.api.key=7piJcW8nUZ9wndQWUFRHU3kEtrvFvqvB7bRIC2RS
email.api.url=https://7srbth8d59.execute-api.eu-central-1.amazonaws.com/live/email
email.api.key=7piJcW8nUZ9wndQWUFRHU3kEtrvFvqvB7bRIC2RS